import {pool} from "../config/db.js";
let auditReady=false;
async function ensureAuditTable(){if(auditReady)return;await pool.query(`CREATE TABLE IF NOT EXISTS admin_audit_log(audit_id INT AUTO_INCREMENT PRIMARY KEY,admin_user_id INT NOT NULL,action VARCHAR(120) NOT NULL,entity_type VARCHAR(60) NOT NULL,entity_id INT NULL,details TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_admin_audit_created(created_at),INDEX idx_admin_audit_admin(admin_user_id),CONSTRAINT fk_admin_audit_user FOREIGN KEY(admin_user_id) REFERENCES users(user_id) ON DELETE RESTRICT ON UPDATE CASCADE)`);auditReady=true;}
async function audit(req,action,type,id,details=''){try{await ensureAuditTable();await pool.query(`INSERT INTO admin_audit_log(admin_user_id,action,entity_type,entity_id,details) VALUES(?,?,?,?,?)`,[req.user.user_id,action,type,id||null,details]);}catch(e){console.error('Admin audit logging failed:',e);}}
const fail=(res,e,m)=>{console.error(m,e);return res.status(500).json({success:false,message:m});};
export async function getManagedUsers(req,res){try{const[users]=await pool.query(`SELECT u.user_id,u.full_name,u.email,u.phone_number,u.role,u.created_at,GROUP_CONCAT(DISTINCT s.stokvel_name ORDER BY s.stokvel_name SEPARATOR ', ') stokvels FROM users u LEFT JOIN stokvel_members sm ON sm.user_id=u.user_id LEFT JOIN stokvels s ON s.stokvel_id=sm.stokvel_id GROUP BY u.user_id ORDER BY u.user_id DESC`);res.json({success:true,users});}catch(e){fail(res,e,'Unable to load managed users.');}}
export async function updateUserRole(req,res){try{const id=Number(req.params.id),{role}=req.body;if(!['member','chairperson','admin'].includes(role))return res.status(400).json({success:false,message:'Invalid role.'});if(id===Number(req.user.user_id)&&role!=='admin')return res.status(400).json({success:false,message:'You cannot remove your own administrator access.'});if(role!=='admin'){const[[count]]=await pool.query(`SELECT COUNT(*) count FROM users WHERE role='admin'`),[[target]]=await pool.query(`SELECT role FROM users WHERE user_id=?`,[id]);if(target?.role==='admin'&&Number(count.count)<=1)return res.status(400).json({success:false,message:'The company must retain at least one administrator.'});}const[r]=await pool.query(`UPDATE users SET role=? WHERE user_id=?`,[role,id]);if(!r.affectedRows)return res.status(404).json({success:false,message:'User not found.'});await audit(req,'Changed user role','user',id,`New role: ${role}`);const[[user]]=await pool.query(`SELECT user_id,full_name,email,phone_number,role,created_at FROM users WHERE user_id=?`,[id]);res.json({success:true,user});}catch(e){fail(res,e,'Unable to update user role.');}}
export async function getStokvelMembers(req,res){try{const[members]=await pool.query(`SELECT u.user_id,u.full_name,u.email,u.phone_number,u.role,sm.joined_at FROM stokvel_members sm JOIN users u ON u.user_id=sm.user_id WHERE sm.stokvel_id=? ORDER BY sm.joined_at,u.full_name`,[Number(req.params.id)]);res.json({success:true,members});}catch(e){fail(res,e,'Unable to load Stokvel members.');}}
export async function addStokvelMember(req,res){try{const[r]=await pool.query(`INSERT INTO stokvel_members(stokvel_id,user_id) VALUES(?,?)`,[Number(req.params.id),Number(req.body.user_id)]);await audit(req,'Added Stokvel member','stokvel',req.params.id,`User ${req.body.user_id} added.`);res.status(201).json({success:true,member_id:r.insertId});}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({success:false,message:'That user is already a member of this Stokvel.'});fail(res,e,'Unable to add Stokvel member.');}}
export async function removeStokvelMember(req,res){try{const[r]=await pool.query(`DELETE FROM stokvel_members WHERE stokvel_id=? AND user_id=?`,[Number(req.params.id),Number(req.params.userId)]);if(!r.affectedRows)return res.status(404).json({success:false,message:'Stokvel membership not found.'});await audit(req,'Removed Stokvel member','stokvel',req.params.id,`User ${req.params.userId} removed.`);res.json({success:true});}catch(e){fail(res,e,'Unable to remove Stokvel member.');}}
export async function getAdminAnalytics(req,res){try{const[[summary]]=await pool.query(`SELECT COUNT(*) total_orders,COALESCE(SUM(CASE WHEN order_status<>'Cancelled' THEN total_amount ELSE 0 END),0) revenue,COALESCE(AVG(CASE WHEN order_status<>'Cancelled' THEN total_amount END),0) average_order_value,SUM(order_status='Completed') completed_orders,SUM(order_status='Cancelled') cancelled_orders FROM order_details`);const[monthlyRevenue]=await pool.query(`SELECT DATE_FORMAT(order_date,'%Y-%m') month,ROUND(SUM(total_amount),2) revenue,COUNT(*) orders FROM order_details WHERE order_status<>'Cancelled' GROUP BY DATE_FORMAT(order_date,'%Y-%m') ORDER BY month DESC LIMIT 12`);const[topProducts]=await pool.query(`SELECT p.product_id,p.product_name,SUM(oi.quantity) units_sold,ROUND(SUM(oi.subtotal),2) sales FROM order_items oi JOIN products p ON p.product_id=oi.product_id JOIN order_details o ON o.order_id=oi.order_id WHERE o.order_status<>'Cancelled' GROUP BY p.product_id,p.product_name ORDER BY units_sold DESC LIMIT 10`);const[stokvelActivity]=await pool.query(`SELECT s.stokvel_id,s.stokvel_name,COUNT(DISTINCT sm.user_id) members,COUNT(DISTINCT o.order_id) orders,COALESCE(SUM(CASE WHEN o.order_status<>'Cancelled' THEN o.total_amount ELSE 0 END),0) spend FROM stokvels s LEFT JOIN stokvel_members sm ON sm.stokvel_id=s.stokvel_id LEFT JOIN order_details o ON o.stokvel_id=s.stokvel_id GROUP BY s.stokvel_id,s.stokvel_name ORDER BY spend DESC`);res.json({success:true,summary,monthlyRevenue,topProducts,stokvelActivity});}catch(e){fail(res,e,'Unable to load admin analytics.');}}
export async function getAuditLog(req,res){try{await ensureAuditTable();const[entries]=await pool.query(`SELECT a.audit_id,a.action,a.entity_type,a.entity_id,a.details,a.created_at,u.full_name admin_name,u.email admin_email FROM admin_audit_log a JOIN users u ON u.user_id=a.admin_user_id ORDER BY a.audit_id DESC LIMIT 200`);res.json({success:true,entries});}catch(e){fail(res,e,'Unable to load audit history.');}}
