import axios from "axios";
import { saveCartState, clearCartState } from "../composables/useCartState.js";
const api=axios.create({baseURL:"http://localhost:4040",headers:{"Content-Type":"application/json"}});api.interceptors.request.use(config=>{const token=localStorage.getItem("token")||localStorage.getItem("sw_token");if(token)config.headers.Authorization=`Bearer ${token}`;return config});
async function refreshCartStorage(){const response=await api.get("/api/cart");saveCartState({items:response.data.items||[],order:response.data.order||null,stokvel:response.data.stokvel||null});return response.data}
export const getStokvels=async()=> (await api.get("/api/stokvels")).data;
export const getProducts=async()=>{const token=localStorage.getItem("token")||localStorage.getItem("sw_token");try{return(await api.get(token?"/api/products/group":"/api/products")).data}catch(error){if(token&&[401,403,500].includes(error.response?.status))return(await api.get("/api/products")).data;throw error}};
export const getProduct=async(id)=>(await api.get(`/api/products/${id}`)).data;export const getCart=async()=>refreshCartStorage();export const addCartItem=async(data)=>{const r=await api.post("/api/cart/items",data);await refreshCartStorage();return r.data};export const updateCartItem=async(id,quantity)=>{const r=await api.patch(`/api/cart/items/${id}`,{quantity});await refreshCartStorage();return r.data};export const removeCartItem=async(id)=>{const r=await api.delete(`/api/cart/items/${id}`);await refreshCartStorage();return r.data};
export const getCurrentOrder=async()=>(await api.get("/api/orders/current")).data;export const getOrderHistory=async()=>(await api.get("/api/orders/history")).data;export const getOrderDetails=async(id)=>(await api.get(`/api/orders/history/${id}`)).data;export const reorderOrder=async(id)=>{const r=await api.post(`/api/reorder/${id}`);await refreshCartStorage();return r.data};
export const getMemberDashboard=async()=>(await api.get("/api/users/member-dashboard")).data;export const getStokvelFeatures=async()=>(await api.get("/api/stokvel-features")).data;export const contributeToStokvel=async(data)=>(await api.post("/api/stokvel-features/contributions",data)).data;export const saveStokvelGoal=async(data)=>(await api.put("/api/stokvel-features/goal",data)).data;export const voteForProduct=async(id)=>(await api.post("/api/stokvel-features/votes",{product_id:id})).data;export const confirmCurrentOrder=async(delivery_address)=>(await api.post("/api/orders/current/confirm",{delivery_address})).data;
export const getPaymentOptions=async()=>(await api.get("/api/payment/current")).data;export const payCurrentOrder=async(data)=>(await api.post("/api/payment/current/pay",data)).data;
export const signup=async(data)=>(await api.post("/api/auth/signup",data)).data;export const login=async(data)=>{const r=await api.post("/api/auth/login",data);if(r.data?.success){localStorage.setItem("token",r.data.token);localStorage.setItem("user",JSON.stringify(r.data.user));localStorage.setItem("stokvel",JSON.stringify(r.data.stokvel));window.dispatchEvent(new Event("login-completed"));window.dispatchEvent(new Event("auth-updated"))}return r.data};export const forgotPassword=async(email)=>(await api.post("/api/auth/forgot-password",{email})).data;export const resetPassword=async(data)=>(await api.post("/api/auth/reset-password",data)).data;export const verifyResetToken=async(token)=>(await api.get("/api/auth/verify-reset-token",{params:{token}})).data;
export const getAdminDashboard=async()=>(await api.get("/api/admin/dashboard")).data;export const getAdminUsers=async()=>(await api.get("/api/admin/users")).data;export const getAdminStokvels=async()=>(await api.get("/api/admin/stokvels")).data;export const getAdminProducts=async()=>(await api.get("/api/admin/products")).data;export const createAdminProduct=async(data)=>(await api.post("/api/admin/products",data)).data;export const updateAdminProduct=async(id,data)=>(await api.put(`/api/admin/products/${id}`,data)).data;export const deleteAdminProduct=async(id)=>(await api.delete(`/api/admin/products/${id}`)).data;export const getAdminSupplierPrices=async()=>(await api.get("/api/admin/supplier-prices")).data;export const createAdminSupplierPrice=async(data)=>(await api.post("/api/admin/supplier-prices",data)).data;export const updateAdminSupplierPrice=async(id,data)=>(await api.put(`/api/admin/supplier-prices/${id}`,data)).data;export const deleteAdminSupplierPrice=async(id)=>(await api.delete(`/api/admin/supplier-prices/${id}`)).data;export const getAdminOrders=async()=>(await api.get("/api/admin/orders")).data;export const updateAdminOrderStatus=async(id,status)=>(await api.patch(`/api/admin/orders/${id}/status`,{status})).data;export const getAdminDeliveries=async()=>(await api.get("/api/admin/deliveries")).data;export const updateAdminDelivery=async(id,data)=>(await api.patch(`/api/admin/deliveries/${id}`,data)).data;export const getAdminManagedUsers=async()=>(await api.get("/api/admin/management/users")).data;export const updateAdminUserRole=async(id,role)=>(await api.patch(`/api/admin/management/users/${id}/role`,{role})).data;export const getAdminStokvelMembers=async(id)=>(await api.get(`/api/admin/management/stokvels/${id}/members`)).data;export const addAdminStokvelMember=async(id,user_id)=>(await api.post(`/api/admin/management/stokvels/${id}/members`,{user_id})).data;export const removeAdminStokvelMember=async(stokvelId,userId)=>(await api.delete(`/api/admin/management/stokvels/${stokvelId}/members/${userId}`)).data;export const getAdminAnalytics=async()=>(await api.get("/api/admin/analytics")).data;export const getAdminAuditLog=async()=>(await api.get("/api/admin/audit-log")).data;export const createSuggestion=async(data)=>(await api.post("/api/suggestions",data)).data;export const getMySuggestions=async()=>(await api.get("/api/suggestions/mine")).data;export const getAllSuggestions=async()=>(await api.get("/api/suggestions/admin")).data;export const updateSuggestion=async(id,status,admin_response)=>(await api.patch(`/api/suggestions/admin/${id}`,{status,admin_response})).data;export default api;
